### ISSUE TITLE
Models need to interface with local and remote stores

### ISSUE THREAD

**Issue by berfarah** [coverhound/active-redux#11]
We want our models to have the following methods:

```js
const Person = Registry.get('Person');
const uuid = process.env.UUID;

// Remote lookup

// Local
Person.clearLocal() // clear entries
Person.findLocal({ uuid }); // Person {}

const person = new Person();
person.updateCache(); // Boolean
person.deleteCache(); // Boolean

// Remote
Person.clear() // clear entries
const person = Person.find({ uuid }); // Promise { person }    catch { undefined }

person.save();                        // Promise { person }    catch { errors }
person.update();                      // Promise { person }    catch { errors }
person.delete();                      // Promise { undefined } catch { errors }
```

**Comment by kylealwyn** [comment]
Some (hopefully) thought provokers:

- Why need a separate findLocal method? Maybe `find` is a robust method that takes a configuration block as second param. Thinking of usage where it would be easier to account for dynamism with these boolean values rather than calling a separate method. Possibly same configuration object for `Person.clear`

```js
// default, same as providing no options
// first looks in local cache, if not found, requests remote resource
Person.find({ uuid }, { local: true, remote: true });

// only look in local
Person.find({ uuid }, { remote: false });

// only look in remote
Person.find({ uuid }, { local: false });
```

- What is update/deleteCache doing?

- `Person.clear()` also needs to clear out all relational entries? posts, comments, etc.

- Attribute setters will dispatch/write into local store. Does update/save remove local entry and write/update remote entry of entity?

**Comment by berfarah** [comment]
Based on our discussion, it sounds like we don't want to incorporate `local` into this library anymore. Local changes will live in the object instance.
